/*!
 * ImideoScript ve3df44b (2015-03-12) | www.imideo.com
 */
var imideo=function(n,H){var ra,sa,ta,ua,fa,va,wa;function xa(a){"undefined"!==typeof console&&console.log(a);C&&u&&C.call(function(){imideo.ui_log(a)})}var ga=!1,r=ga?function(a){xa(a)}:function(){},m=n.document,K=m.location,U=n.encodeURIComponent,I=n.setTimeout,L=n.clearTimeout,V=n.parseInt,W=n.isNaN,q=!1,u=!1,p={ALL:{visible:!1,design:"normal"},MBC:{visible:!1,design:"normal"},SBS:{visible:!1,design:"normal"},SBS_ESPN:{visible:!1,design:"normal"},CJ_ENM:{visible:!1,design:"normal"},MNET:{visible:!1,
design:"normal"},ON_STYLE:{visible:!1,design:"normal"},OCN:{visible:!1,design:"normal"},OLIVE:{visible:!1,design:"normal"},STORY_ON:{visible:!1,design:"normal"},TVN:{visible:!1,design:"normal"},XTM:{visible:!1,design:"normal"}},w="";if(!function(){var a=m.getElementsByTagName("head")[0],f=a.getElementsByTagName("script"),k=m.getElementsByTagName("body")[0],l=f.length-1,j=!0;try{if(j=k.getAttribute("contentEditable"),"true"!==j)return!1}catch(h){return!1}do k=f[l],(k.src&&-1<k.src.indexOf("static.image2play.com")||
-1<k.text.indexOf("static.image2play.com"))&&a.removeChild(k);while(l--);return!0}()){var y;y=m.getElementsByTagName("script");var s=y.length,X={},ya=0;"undefined"!==typeof n.imideo_appkey&&"f8da5Hf0d7jad09m4abdb09c1V7702kcc0cx28a4"===n.imideo_appkey&&(p.KBS={visible:!1,design:"normal"});for(var ha=0;ha<s;ha++){var t=y[ha].id;0===t.indexOf("i2p-")&&(X[t]=m.getElementById(t).src,ya++,"i2p-extension"===t?(0<X[t].indexOf("imideo.publisher.js")?(p.ALL={visible:!0,design:"normal"},q=!0):0<X[t].indexOf("imideo.samsung.js")?
(p.KBS={visible:!0,design:"samsung"},p.KBS1={visible:!0,design:"samsung"},p.KBS2={visible:!0,design:"samsung"},p.MBN={visible:!0,design:"samsung"},p.TV_CHOSUN={visible:!0,design:"samsung"},p.CHANNEL_A={visible:!0,design:"samsung"},p.JTBC={visible:!0,design:"samsung"},q=!1,u=!0):(p.ALL={visible:!0,design:"normal"},q=!1),w=m.getElementById(t).src):"i2p-extension-nate"===t?(p.KBS={visible:!0,design:"normal"},p.KBS1={visible:!0,design:"normal"},p.KBS2={visible:!0,design:"normal"},p.MBN={visible:!0,design:"normal"},
p.TV_CHOSUN={visible:!0,design:"normal"},p.CHANNEL_A={visible:!0,design:"normal"},p.JTBC={visible:!0,design:"normal"},q=!0,w=m.getElementById(t).src):"i2p-extension-zum"===t?(p.KBS={visible:!0,design:"altoolbar"},p.KBS1={visible:!0,design:"altoolbar"},p.KBS2={visible:!0,design:"altoolbar"},p.MBN={visible:!0,design:"altoolbar"},p.TV_CHOSUN={visible:!0,design:"altoolbar"},p.CHANNEL_A={visible:!0,design:"altoolbar"},p.JTBC={visible:!0,design:"altoolbar"},q=!0,w=m.getElementById(t).src):"i2p-extension-est"===
t&&!1===p.ALL.visible&&(p.ALL={visible:!0,design:"altoolbar"},q=!1,w=m.getElementById(t).src),0<X[t].indexOf("debug=true")&&(r=(ga=!0,function(a){xa(a)})))}y=ya;s=(s=m.getElementById("imideo-setting"))?s.getAttribute("content").toLowerCase():"yes";if("undefined"!==typeof imideo||"no"===s){try{if("undefined"===typeof imideo.SCRIPT_IDS_LENGTH||y===imideo.SCRIPT_IDS_LENGTH)return r("PASS"),imideo}catch(Ra){return r("PASS"),imideo}try{imideo.set_script_config(p),imideo.set_publisher_script(q),imideo.script_parameter(w),
imideo.ui_refresh()}catch(Sa){}return imideo}var D="",M="",N=!1,z=!1,E=K.href,O=K.protocol+"//",ia=!1,za=!1,Y="timeout",ja="not_matched";ra=0;sa=1;ta=2;ua=3;fa=4;va=5;wa=6;var J=-1,Z="",ka=200,la=null,s=function(){this.callbacks=[]};s.prototype={add:function(a){this.callbacks.push(a)},run:function(){for(var a=this.callbacks.length,f=0;f<a;f++)this.callbacks[f]();this.callbacks=[]}};var Aa=function(a){function f(a,b,c,d,f,e){a=h(h(b,a),h(d,e));return h(a<<f|a>>>32-f,c)}function k(a,b,c,d,e,g,k){return f(b&
c|~b&d,a,b,e,g,k)}function l(a,b,c,d,e,g,k){return f(b&d|c&~d,a,b,e,g,k)}function j(a,b,c,d,e,g,k){return f(c^(b|~d),a,b,e,g,k)}function h(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535}for(var d=Array(a.length>>2),b=0;b<d.length;b++)d[b]=0;for(b=0;b<8*a.length;b+=8)d[b>>5]|=(a.charCodeAt(b/8)&255)<<b%32;a=8*a.length;d[a>>5]|=128<<a%32;d[(a+64>>>9<<4)+14]=a;a=1732584193;for(var b=-271733879,c=-1732584194,e=271733878,g=0;g<d.length;g+=16){var m=a,p=b,n=c,r=e;a=k(a,b,c,e,d[g+
0],7,-680876936);e=k(e,a,b,c,d[g+1],12,-389564586);c=k(c,e,a,b,d[g+2],17,606105819);b=k(b,c,e,a,d[g+3],22,-1044525330);a=k(a,b,c,e,d[g+4],7,-176418897);e=k(e,a,b,c,d[g+5],12,1200080426);c=k(c,e,a,b,d[g+6],17,-1473231341);b=k(b,c,e,a,d[g+7],22,-45705983);a=k(a,b,c,e,d[g+8],7,1770035416);e=k(e,a,b,c,d[g+9],12,-1958414417);c=k(c,e,a,b,d[g+10],17,-42063);b=k(b,c,e,a,d[g+11],22,-1990404162);a=k(a,b,c,e,d[g+12],7,1804603682);e=k(e,a,b,c,d[g+13],12,-40341101);c=k(c,e,a,b,d[g+14],17,-1502002290);b=k(b,c,
e,a,d[g+15],22,1236535329);a=l(a,b,c,e,d[g+1],5,-165796510);e=l(e,a,b,c,d[g+6],9,-1069501632);c=l(c,e,a,b,d[g+11],14,643717713);b=l(b,c,e,a,d[g+0],20,-373897302);a=l(a,b,c,e,d[g+5],5,-701558691);e=l(e,a,b,c,d[g+10],9,38016083);c=l(c,e,a,b,d[g+15],14,-660478335);b=l(b,c,e,a,d[g+4],20,-405537848);a=l(a,b,c,e,d[g+9],5,568446438);e=l(e,a,b,c,d[g+14],9,-1019803690);c=l(c,e,a,b,d[g+3],14,-187363961);b=l(b,c,e,a,d[g+8],20,1163531501);a=l(a,b,c,e,d[g+13],5,-1444681467);e=l(e,a,b,c,d[g+2],9,-51403784);c=l(c,
e,a,b,d[g+7],14,1735328473);b=l(b,c,e,a,d[g+12],20,-1926607734);a=f(b^c^e,a,b,d[g+5],4,-378558);e=f(a^b^c,e,a,d[g+8],11,-2022574463);c=f(e^a^b,c,e,d[g+11],16,1839030562);b=f(c^e^a,b,c,d[g+14],23,-35309556);a=f(b^c^e,a,b,d[g+1],4,-1530992060);e=f(a^b^c,e,a,d[g+4],11,1272893353);c=f(e^a^b,c,e,d[g+7],16,-155497632);b=f(c^e^a,b,c,d[g+10],23,-1094730640);a=f(b^c^e,a,b,d[g+13],4,681279174);e=f(a^b^c,e,a,d[g+0],11,-358537222);c=f(e^a^b,c,e,d[g+3],16,-722521979);b=f(c^e^a,b,c,d[g+6],23,76029189);a=f(b^c^
e,a,b,d[g+9],4,-640364487);e=f(a^b^c,e,a,d[g+12],11,-421815835);c=f(e^a^b,c,e,d[g+15],16,530742520);b=f(c^e^a,b,c,d[g+2],23,-995338651);a=j(a,b,c,e,d[g+0],6,-198630844);e=j(e,a,b,c,d[g+7],10,1126891415);c=j(c,e,a,b,d[g+14],15,-1416354905);b=j(b,c,e,a,d[g+5],21,-57434055);a=j(a,b,c,e,d[g+12],6,1700485571);e=j(e,a,b,c,d[g+3],10,-1894986606);c=j(c,e,a,b,d[g+10],15,-1051523);b=j(b,c,e,a,d[g+1],21,-2054922799);a=j(a,b,c,e,d[g+8],6,1873313359);e=j(e,a,b,c,d[g+15],10,-30611744);c=j(c,e,a,b,d[g+6],15,-1560198380);
b=j(b,c,e,a,d[g+13],21,1309151649);a=j(a,b,c,e,d[g+4],6,-145523070);e=j(e,a,b,c,d[g+11],10,-1120210379);c=j(c,e,a,b,d[g+2],15,718787259);b=j(b,c,e,a,d[g+9],21,-343485551);a=h(a,m);b=h(b,p);c=h(c,n);e=h(e,r)}d=[a,b,c,e];a="";for(b=0;b<32*d.length;b+=8)a+=String.fromCharCode(d[b>>5]>>>b%32&255);d=a;a="";for(c=0;c<d.length;c++)b=d.charCodeAt(c),a+="0123456789abcdef".charAt(b>>>4&15)+"0123456789abcdef".charAt(b&15);return a},P,Ba=function(){return/loaded|interactive|complete/.test(m.readyState)},v=function(){!z&&
m.addEventListener?n.removeEventListener("load",v,!1):n.detachEvent("onload",v);ma.run();$=!0},aa=function(){!z&&m.addEventListener?(r("DOMContentLoaded"),m.removeEventListener("DOMContentLoaded",aa,!1),v()):Ba()&&(r("DOMContentLoaded"),m.detachEvent("onreadystatechange",aa),v())},Ca=function(a){var f={};if(-1<a.indexOf("?")){a=a.split("?").pop().split("&");for(var k=0;k<a.length;k++){var l=a[k].split("=");f[l[0]]=l[1]}}a=f.appkey;!q&&!u&&!a?a="H604cJ529fb7ef7k420049ffff6619M1b4f4c5fd":u&&!a&&(a=
"Bc6c0d03d6P524ft75a43ad8fs0721t8ac7Nc45e");D=a;a=f.extkey;!q&&!u&&!a?a="undefined"!==typeof imideo_identifier?imideo_identifier:"":u&&!a&&(a="3e4c704b-f182-43e4-bd43-1448a859ba6d");M=a;(Z=(a=f.params)?decodeURIComponent(a):"")&&(Z="&"+Z);a=V(f.grade,10);W(a)&&(a=200);ka=a;la=f;r("APPKEY "+D+", EXTKEY "+M+", GRADE "+ka)},na=function(){return"Microsoft Internet Explorer"===navigator.appName},$=!1,ma=new s,z=na();ma.add(function(){function a(a){try{var b=n[a];delete n[a];var d=n[a];n[a]=b;return d}catch(f){return function(){try{return n.constructor.prototype[a].apply(n,
arguments)}catch(b){return n[a]}}}}function f(){var a=-1;na()&&/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return a}function k(){if(-1!==E.indexOf("cafe.naver.com/ArticleRead.nhn"))return delete Object.prototype.toJSON,!0;try{var a=!(na()&&9>f()),b;for(b in Object.prototype){if(!a)return!1;Object.defineProperty(Object.prototype,b,{value:Object.prototype[b],enumerable:!1})}}catch(d){}return!0}Ca(w);var l;l="now.olleh.com www.olleh.com coupang.com comic.naver.com 11st.co.kr ticketmonster.co.kr gmarket.co.kr esmplus.com shopping.naver.com www.naver.com auction.co.kr map.daum.net cu-media.co.kr hyplove.co.kr unimedihospital.co.kr sktsdinfo.com m.naver.com m.blog.naver.com m.cafe.daum.net m.cafe.naver.com postman.co.kr youku.com 77wh.blogspot.kr page.uplus.co.kr m.wedisk.co.kr hyundaihmall.com encar.com halfclub.com gsshop.com m.bobaedream.co.kr m.nate.com m.webtoon.daum.net www.gomdisk.net mobile.sportsseoul.com m.comics.nate.com m.cartoon.media.daum.net m.imgur.com m.okoutdoor.com m.sports.media.daum.net 19insidenet.com lotte.com www.stylenanda.com m.shop.naver.com www.lgfashionshop.com www.stylenanda.com www.oclock.co.kr shop.beautynet.co.kr www.soo-a.co.kr wowtv.co.kr inisland.co.kr coway.co.kr wemakeprice.com beeg.com anncoll.com jtbc.joins.com shilla.net shilladfs.com paris.co.kr beautifulstore.org plus.kakao.com plus-talk.kakao.com befe.co.kr buttoney.com 365mc.co.kr wownet.co.kr wowfa.co.kr landcenter.co.kr kamastudio.co.kr mingky5.com xnxx.com map.naver.com milkcocoa.co.kr lotteimall.com ippngirl.co.kr naning9.com cjmall.com yes24.com littleblack.co.kr dabagirl.co.kr pdpop.com ndrive2.naver.com nv2.ad.naver.com track.tiara.daum.net bryc.co.kr dyimin.com bestent.hosting.urdv.net bestent.co.kr joyzen.co.kr luchiafood.com atofinemall.com".split(" ");
var j=l.length,h=!0;do if(-1!==E.indexOf(l[j-1])){h=!1;break}while(j--);if(l=h)if(l=k()){l=!1;do if(D&&M){if(q){h={"06fd0a766f7699d6dc0664c98dcaafae":{com:{imideo:1,imideomall:1},221:1},"07ee71747102ebefc699b4123beca584":1,"43359199b9f59146c1d3bbafa97c4822":{com:{soompi:1}},a8b7ec27a12e5709ccae1961341b72b1:1,"15d28f94d6be89579adcd6fb4d7ad73b":1,"2f238e88c451498d381b2133ea1eb6b2":1,"17d3ae82b7a3352c68a0a91f9bc910a3":1,"0e0489c01079790c70cb82d8bfc42cba":1,"9d49316d73a7340ee4d929f2c8108b10":1,ebd264723c9bd1b6b966da1997038d14:1};
h=h[Aa(D)];if(j=h!==H)a:{for(var j=K.hostname,j=j.split(".").reverse(),d=j.length,b=0;b<d&&"number"!==typeof h;b++)if(h=h[j[b]],h===H){j=!1;break a}j=1===h||0===h&&b===d}if(!j)break}l=!0}while(0)}N=l;-1!==E.indexOf("facebook.com")&&(l=f(),-1!==l&&8>l?N=!1:(a("setInterval"),I=a("setTimeout")));q&&(ia=/^https?:\/\/((((www(\.dev)?)|m)\.)?imideo\.com|121\.78\.228\.221)/i.test(E),za=/^http:\/\/isplus\.joins\.com\/?/i.test(E)&&"/"===K.pathname);r("PAGE_URL "+E+", IS_ENABLED "+N+", MSIE "+z)});r("ready_promise : "+
m.readyState);if(Ba())r("is_document_ready_state start ready()"),v&&I(v,1);else if(!z&&m.addEventListener)r("wait for DOMContentLoaded"),m.addEventListener("DOMContentLoaded",aa,!1),n.addEventListener("load",v,!1);else{r("wait for DOMContentLoaded");m.attachEvent("onreadystatechange",aa);n.attachEvent("onload",v);var ba=!1;try{ba=null==n.frameElement&&m.documentElement}catch(Ta){}ba&&ba.doScroll&&function f(){if(!$){try{ba.doScroll("left")}catch(k){return I(f,50)}v()}}()}P={script_parameter:Ca,is_ready:$,
ready:function(f){$?f():ma.add(f)}};var A,Ea=function(f){if(0<=m.location.hostname.indexOf("daum")&&_regexp_nomatch.test(f.src))return!1;if(ia||za)return Da.test(f.src);var k=f.width;f=f.height;var l=k/f;return k>=Q&&f>=R&&20>l&&0.03<l},Ma=function(f,k){S.query_i2p(f,function(l){C.call(function(){k.clips=l;imideo.ui_add&&imideo.ui_add(f,k)})},function(){k.filtered=!0;k.objs=[]},!1)},Ga=function(){var f=m.images,k=f.length,l,j,h;for(l in F)F[l].objs=[];for(l=0;l<k;l++){j=f[l];h=j.src;var d=Fa.exec(h);
h=d?d[1]:h;Ea(j)&&(h in F?(d=F[h],!0!==d.filtered&&d.objs.push(j)):(r("selected: "+h),d={objs:[j]},F[h]=d,Ma(h,d)))}},Ha=function(){Ga();B&&(L(B),x=u?Math.min(x+Na,Oa):Math.min(x+Pa,Qa),B=I(Ha,x))},ca=!1,Ia=!1,Qa=6E3,Pa=500,Oa=1E3,Na=100,x,B,F,Q,R,Fa,Da;A={start:function(){if(!ca){if(!Ia){Ia=!0;Q=V(la.minwidth,10);if(W(Q)||50>Q)Q=q?150:u?200:290;R=V(la.minheight,10);if(W(R)||50>R)R=q?75:150;Fa=/^(http:\/\/thumb\.(mt\.co\.kr|mtstarnews\.com)\/[^\?]*)\?time=\d*$/i;Da=/^https?:\/\/[^#]*#forcedmatch/i;
_regexp_nomatch=/^https?:\/\/[^#]*#no_imideo/i}ca=!0;x=u?500:1E3;F={};Ga();B=I(Ha,x)}},stop:function(){ca&&(ca=!1,B&&(L(B),B=null))},is_valid_image:Ea};var S,oa=function(f,k,l){var j=new Image;l.push("appkey="+D);l.push("extension_key="+M);l.push("page_url="+U(m.location.href));l.push("image_url="+U(k));j.src=O+("i2p.enswer.net/v1/stat/"+f+"/")+"?"+l.join("&")},Ja=function(f,k,l){function j(){try{delete n[h]}catch(b){n[h]=H}}var h=("imideo_jsonp"+(l||Math.random())).replace(".",""),d=m.head||m.getElementsByTagName("head")[0]||
m.documentElement,b;n[h]=function(b){k(b);j()};b=m.createElement("script");b.src=f+"&callback="+h;b.async="async";b.onload=b.onreadystatechange=function(c,f){if(f||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,d&&b.parentNode&&d.removeChild(b),d=b=H};d.insertBefore(b,d.firstChild);return{abort:function(){if(b)b.onload(0,1);j();n[h]=function(){}}}},Ka=1E4,G={};S={query_i2p:function(f,k,l,j){function h(){q&&(q.abort(),q=null);m&&(L(m),m=null)}function d(){delete G[f];
h();g&&(L(g),g=null);t&&(t.abort(),t=null)}function b(b){var d=j?"manual_recognize_done":"auto_recognize_done";b=["width=0&height=0","duration="+((new Date).getTime()-n),"status_code="+u,"clip_ids="+b];oa(d,f,b)}function c(c){d();var e="";c===Y&&0<p?(e="NO_RESPONSE",r("no_response: "+f)):c===Y&&(e="TIMEOUT",r("timeout: "+f));J>=fa&&(e="OVMS_TIMEOUT",r("ovms_timeout: "+f));0.1>Math.random()&&b(e);l(c)}function e(){h();var n=["appkey="+D,"src="+U(f),"type=url"];j&&n.push("mode=manual");J=ra;var s="i2p.enswer.net/v2/image/",
v=null;if("P7cc1x1ce3L8b0aF6d0d008b4o042eKd74cU39eb"===D||"d7a7eq2226he8b8Jed90Yedf1f5887h52e4Ce95e"===D)s="api.imideo.com/v2/image/",v=Aa(U(f)),"https://"===O&&(s="i2p.enswer.net/v2/image/");q=Ja(O+s+"?"+n.join("&")+Z,function(h){q=null;u=h.status_code;var j;if(j=h.match){var n={},s=[],v=j.length,C,B,w,y,z;for(y=0;y<v;y++){var E=[];B=j[y];C=B.length;for(z=0;z<C;z++)w=B[z],"rtmp"===w.clip_type&&!(w.clip_id in n)&&(n[w.clip_id]=!0,E.push(w.clip_id));0<E.length&&s.push(E)}j=s}else j=[];if(0<j.length){J=
sa;j.iid=h.image_id||"";var A=j;j=A.length;h="[";for(n=0;n<j;n++)0<n&&(h+=","),h+='["'+A[n].join('","')+'"]';h+="]";r("matched: "+f);d();J=fa;g=I(function(){c(Y)},Ka);var F=f,x;x=Ja(O+"ovms.enswer.net/v3/enable_streaming?"+["clip_ids="+h,"thumbnail=1"].join("&"),function(c){delete G[F];x=null;var e=c.results;c=[];for(var g,h=null,j=-1,m={},n=0;n<e.length;n++)if(g=e[n],!(g.error!==H&&620!==g.error.code||g.content_id in m&&!0!==g["default"])){m[g.content_id]=!0;var p=g,q=g.title,s=g.ep;q?!W(parseFloat(s))&&
isFinite(s)&&(q=q+" "+s+"\ud68c"):q="\uc81c\ubaa9\uc5c6\uc74c";p.title_display=q;g.content_distributor_display={CHANNEL_A:"CHANNEL A",MNET:"Mnet",ON_STYLE:"On Style",SBS_ESPN:"SBS ESPN",TVN:"tvN",TV_CHOSUN:"TV\uc870\uc120"}[g.content_distributor]||g.content_distributor;g.airdate=g.airdate||"";if(!0===g["default"]){h=!1;for(p=0;p<c.length;p++)if(c[p].content_id===g.content_id){c[p]=g;h=!0;break}h||c.push(g);h=g}else 0>j&&"JTBC"===g.content_provider&&(j=c.length),c.push(g)}"ma5c5q2d1aX2cfcO7e70seb4bIcbe0E6a16j48ab"===
D&&(null!==h&&"JTBC"!==h.content_provider&&-1<j)&&(h=c[j]);null===h&&0<c.length&&(h=c[0]);c.default_item=h;if((e=K.hostname.match(/\.(joins|koreadaily)\.com/i))&&(0<e.length&&null!==h&&"NEWS"===h.genre&&"JTBC"!==h.content_provider)&&!(-1<j))c=[],c.default_item=H;if(0<c.length){J=va;r("ovms_received: "+f);d();c.iid=A.iid;j="";e=c.length;for(g=0;g<e;g++)0<j.length&&(j+=","),j+=c[g].clip_id;b(j+",OVMS");c.default_item&&!0!==c.default_item.adult_content&&k(c)}else c=ja,d(),J=wa,c===ja?(j="OVMS_EMPTY",
r("ovms_empty: "+f)):(j="OVMS_ERROR",r("ovms_error: "+f)),b(A[0][0]+","+j),l(c)});t=G[F]={abort:function(){x&&x.abort();delete G[F];x=null}}}else 300>V(h.status_code)?(r("rematch("+p+"): "+f),J=ta,p++,m&&L(m),m=I(e,3>p?3E3:1E3)):(r("not matched: "+f),J=ua,c(ja))},v)}var g=null,m=null,p=0,n=(new Date).getTime(),q=null,t=null,u="",g=I(function(){c(Y)},Ka);j&&oa("manual_recognize",f,["width=0","height=0"]);e();return G[f]={abort:function(){d()}}},stop:function(){for(var f in G)G[f].abort(),delete G[f];
G={}},send_stats:oa};var C,pa=new s,da=0;C={call:function(f){switch(da){case 0:pa.add(f);f=m.getElementById("i2p-extension-ui");var k;a:{k=m.getElementsByTagName("style");for(var l=k.length,j=0;j<l;j++)if(0===(z?k[j].styleSheet.cssText:k[j].innerHTML).indexOf(".imideo-c")){k=k[j];break a}k=H}f&&(f.parentNode.removeChild(f),k&&k.parentNode.removeChild(k));da=1;f=u?"imideo.mobile.ui.js":"imideo.ui.js";var h=m.createElement("script");h.type="text/javascript";h.id="i2p-extension-ui";h.async="async";h.src=
O+"static.image2play.com/"+f+"?_=1.1.2";"utf-8"!=m.charset&&(h.charset="utf-8");h.onload=h.onreadystatechange=function(){if(2!==da&&(!h.readyState||/loaded|complete/.test(h.readyState)))da=2,h.onload=h.onreadystatechange=null,h=H,ga&&u&&imideo.ui_log_start(),pa.run()};m.getElementsByTagName("head")[0].appendChild(h);break;case 1:pa.add(f);break;case 2:f()}}};var qa,La=function(){ea&&(ea.abort(),ea=null)},ea=null;qa={match:function(f){La();C.call(function(){imideo.ui_match_start()});ea=S.query_i2p(f,
function(k){C.call(function(){imideo.ui_match_end(f,k.iid,k.default_item)})},function(){C.call(function(){imideo.ui_match_end()})},!0)},stop:La};var s=function(){P.ready(function(){!T&&N&&(r("started"),A.start(),T=!0)})},T=!1;(q||u)&&s();return{start:s,stop:function(){P.ready(function(){if(T){r("stopped");A.stop();S.stop();qa.stop();T=!1;try{imideo.ui_stop()}catch(f){}}})},match:function(f){P.ready(function(){N&&(r("match "+f),qa.match(f))})},refresh:function(){if(T){A.stop();A.start();try{imideo.ui_refresh()}catch(f){}}},
is_valid_image:A.is_valid_image,APPKEY:function(){return D},EXTKEY:function(){return M},GRADE:function(){return ka},PUBLISHER_SCRIPT:q,set_publisher_script:function(f){q=f},set_script_config:function(f){p=f},get_script_config:function(){return p},IS_IMIDEO_COM:function(){return ia},send_stats:S.send_stats,script_parameter:P.script_parameter,VERSION:"1.0.6",SCRIPT_IDS_LENGTH:y}}}(window);
