openapi: 3.0.0
info:
  title: 'Search API'
  version: 1.0.0
servers:
- url: 
  description: Current host server
- url: https:your-server.com
  description: Prod server
paths:
  /search:
    post:
      summary: 'Returns most accurate search result object'
      description: 'Search for an object, if found return it!'
      requestBody:
        description: 'Client side search object'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientSearchObject'
      responses:
        '200':
          description: Success
        '404':
          description: Resource Not Found
components:
  schemas:
    ClientSearchObject:
      type: object
      required:
      - typeName
      properties:
        typeName:
          type: string
        query:
          type: string
